# Generated by Django 5.2.5 on 2025-11-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trabajo_id', models.IntegerField(db_index=True, unique=True, verbose_name='ID del Trabajo')),
                ('vehiculo_placa', models.CharField(db_index=True, max_length=20)),
                ('vehiculo_marca', models.CharField(blank=True, max_length=100, null=True)),
                ('vehiculo_modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('cliente_nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_ingreso', models.DateTimeField(db_index=True)),
                ('fecha_ultimo_estado', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('estado_actual', models.CharField(db_index=True, max_length=20)),
                ('total_acciones', models.IntegerField(default=0)),
                ('acciones_completadas', models.IntegerField(default=0)),
                ('cantidad_repuestos', models.IntegerField(default=0, verbose_name='Cantidad de Repuestos')),
                ('repuestos_instalados', models.IntegerField(default=0)),
                ('total_mano_obra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_repuestos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Repuestos (Monto)')),
                ('total_general', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_abonos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('porcentaje_avance', models.IntegerField(default=0)),
                ('porcentaje_cobrado', models.IntegerField(default=0)),
                ('dias_en_taller', models.IntegerField(default=0)),
                ('dias_desde_entrega', models.IntegerField(blank=True, null=True)),
                ('mecanicos_asignados', models.CharField(blank=True, help_text='IDs de mecánicos separados por comas', max_length=500, null=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resumen de Trabajo',
                'verbose_name_plural': 'Resúmenes de Trabajos',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.AlterModelOptions(
            name='registroevento',
            options={'ordering': ['-fecha_evento', '-creado_en'], 'verbose_name': 'Registro de Evento', 'verbose_name_plural': 'Registros de Eventos'},
        ),
        migrations.AddField(
            model_name='registroevento',
            name='accion_id',
            field=models.IntegerField(blank=True, help_text='ID de la acción relacionada (si aplica)', null=True, verbose_name='ID de Acción'),
        ),
        migrations.AddField(
            model_name='registroevento',
            name='accion_nombre',
            field=models.CharField(blank=True, help_text='Nombre de la acción al momento del evento', max_length=200, null=True, verbose_name='Nombre de Acción'),
        ),
        migrations.AddField(
            model_name='registroevento',
            name='cliente_nombre',
            field=models.CharField(blank=True, help_text='Nombre del cliente al momento del evento', max_length=200, null=True, verbose_name='Nombre del Cliente'),
        ),
        migrations.AddField(
            model_name='registroevento',
            name='componente_nombre',
            field=models.CharField(blank=True, help_text='Componente relacionado (si aplica)', max_length=200, null=True, verbose_name='Nombre de Componente'),
        ),
        migrations.AddField(
            model_name='registroevento',
            name='creado_en',
            field=models.DateTimeField(null=True, db_index=True, verbose_name='Fecha de Creación del Registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroevento',
            name='diagnostico_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='ID del diagnóstico relacionado', null=True, verbose_name='ID del Diagnóstico'),
        ),
        migrations.AddField(
            model_name='registroevento',
            name='dias_en_taller',
            field=models.IntegerField(blank=True, help_text='Días que estuvo en el taller al momento del evento', null=True, verbose_name='Días en Taller'),
        ),
        migrations.AddField(
            model_name='registroevento',
            name='estado_anterior',
            field=models.CharField(blank=True, help_text='Estado previo (para cambios de estado)', max_length=20, null=True, verbose_name='Estado Anterior'),
        ),
        migrations.AddField(
            model_name='registroevento',
            name='estado_nuevo',
            field=models.CharField(blank=True, help_text='Nuevo estado (para cambios de estado)', max_length=20, null=True, verbose_name='Estado Nuevo'),
        ),
        migrations.AddField(
            model_name='registroevento',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Fecha en que se entregó el vehículo (si aplica)', null=True, verbose_name='Fecha de Entrega'),
        ),
        migrations.AddField(
            model_name='registroevento',
            name='fecha_ingreso',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Fecha en que ingresó el vehículo al sistema', null=True, verbose_name='Fecha de Ingreso'),
        ),
        migrations.AddField(
            model_name='registroevento',
            name='mecanico_id',
            field=models.IntegerField(blank=True, help_text='Mecánico relacionado (si aplica)', null=True, verbose_name='ID del Mecánico'),
        ),
        migrations.AddField(
            model_name='registroevento',
            name='mecanico_nombre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Mecánico'),
        ),
        migrations.AddField(
            model_name='registroevento',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto relacionado (abonos, acciones, repuestos)', max_digits=10, null=True, verbose_name='Monto'),
        ),
        migrations.AddField(
            model_name='registroevento',
            name='repuesto_cantidad',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad de Repuesto'),
        ),
        migrations.AddField(
            model_name='registroevento',
            name='repuesto_id',
            field=models.IntegerField(blank=True, help_text='ID del repuesto relacionado (si aplica)', null=True, verbose_name='ID de Repuesto'),
        ),
        migrations.AddField(
            model_name='registroevento',
            name='repuesto_nombre',
            field=models.CharField(blank=True, help_text='Nombre del repuesto al momento del evento', max_length=200, null=True, verbose_name='Nombre de Repuesto'),
        ),
        migrations.AddField(
            model_name='registroevento',
            name='total_general',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total general al momento del evento', max_digits=10, null=True, verbose_name='Total General'),
        ),
        migrations.AddField(
            model_name='registroevento',
            name='total_mano_obra',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total de mano de obra al momento del evento', max_digits=10, null=True, verbose_name='Total Mano de Obra'),
        ),
        migrations.AddField(
            model_name='registroevento',
            name='total_repuestos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total de repuestos al momento del evento', max_digits=10, null=True, verbose_name='Total Repuestos'),
        ),
        migrations.AddField(
            model_name='registroevento',
            name='trabajo_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='ID del trabajo relacionado (null si es solo diagnóstico, puede no existir si fue eliminado)', null=True, verbose_name='ID del Trabajo'),
        ),
        migrations.AddField(
            model_name='registroevento',
            name='usuario_id',
            field=models.IntegerField(blank=True, help_text='Usuario que realizó la acción', null=True, verbose_name='ID del Usuario'),
        ),
        migrations.AddField(
            model_name='registroevento',
            name='usuario_nombre',
            field=models.CharField(blank=True, help_text='Nombre del usuario al momento del evento', max_length=150, null=True, verbose_name='Nombre del Usuario'),
        ),
        migrations.AddField(
            model_name='registroevento',
            name='vehiculo_id',
            field=models.IntegerField(db_index=True, default=1, help_text='ID del vehículo relacionado', verbose_name='ID del Vehículo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroevento',
            name='vehiculo_marca',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca del Vehículo'),
        ),
        migrations.AddField(
            model_name='registroevento',
            name='vehiculo_modelo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo del Vehículo'),
        ),
        migrations.AddField(
            model_name='registroevento',
            name='vehiculo_placa',
            field=models.CharField(db_index=True, default=1, help_text='Placa almacenada al momento del evento', max_length=20, verbose_name='Placa del Vehículo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registroevento',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción adicional del evento', null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='registroevento',
            name='fecha_evento',
            field=models.DateTimeField(db_index=True, help_text='Fecha y hora exacta en que ocurrió el evento', verbose_name='Fecha del Evento'),
        ),
        migrations.AlterField(
            model_name='registroevento',
            name='tipo_evento',
            field=models.CharField(choices=[('diagnostico_creado', 'Diagnóstico Creado'), ('diagnostico_aprobado', 'Diagnóstico Aprobado'), ('ingreso', 'Ingreso de Vehículo'), ('cambio_estado', 'Cambio de Estado'), ('accion_completada', 'Acción Completada'), ('accion_pendiente', 'Acción Marcada como Pendiente'), ('repuesto_instalado', 'Repuesto Instalado'), ('repuesto_pendiente', 'Repuesto Marcado como Pendiente'), ('entrega', 'Vehículo Entregado'), ('abono', 'Abono/Pago Recibido'), ('mecanico_asignado', 'Mecánico Asignado'), ('mecanico_removido', 'Mecánico Removido'), ('foto_agregada', 'Foto Agregada'), ('observacion_agregada', 'Observación Agregada')], db_index=True, max_length=30, verbose_name='Tipo de Evento'),
        ),
        migrations.AddIndex(
            model_name='registroevento',
            index=models.Index(fields=['trabajo_id', 'tipo_evento', 'fecha_evento'], name='estadistica_trabajo_f05126_idx'),
        ),
        migrations.AddIndex(
            model_name='registroevento',
            index=models.Index(fields=['vehiculo_id', 'fecha_evento'], name='estadistica_vehicul_c66fda_idx'),
        ),
        migrations.AddIndex(
            model_name='registroevento',
            index=models.Index(fields=['fecha_ingreso', 'fecha_entrega'], name='estadistica_fecha_i_2d71c3_idx'),
        ),
        migrations.AddIndex(
            model_name='registroevento',
            index=models.Index(fields=['tipo_evento', 'fecha_evento'], name='estadistica_tipo_ev_2d9094_idx'),
        ),
        migrations.AddIndex(
            model_name='registroevento',
            index=models.Index(fields=['vehiculo_placa', 'fecha_evento'], name='estadistica_vehicul_fcf0a8_idx'),
        ),
        migrations.AddIndex(
            model_name='resumentrabajo',
            index=models.Index(fields=['estado_actual', 'fecha_ingreso'], name='estadistica_estado__52d364_idx'),
        ),
        migrations.AddIndex(
            model_name='resumentrabajo',
            index=models.Index(fields=['fecha_entrega', 'dias_desde_entrega'], name='estadistica_fecha_e_2a3873_idx'),
        ),
        migrations.AddIndex(
            model_name='resumentrabajo',
            index=models.Index(fields=['vehiculo_placa', 'fecha_ingreso'], name='estadistica_vehicul_38b066_idx'),
        ),
    ]
