# Generated by Django 5.2.5 on 2025-11-21 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_prefijorepuesto'),
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repuestoexterno',
            options={'ordering': ['-veces_usado', '-fecha_creacion'], 'verbose_name': 'Repuesto Externo', 'verbose_name_plural': 'Repuestos Externos'},
        ),
        migrations.AddField(
            model_name='repuesto',
            name='carroceria',
            field=models.CharField(blank=True, default='yyyyyy', max_length=100, null=True, verbose_name='Carrocería'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='cod_prov',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código Proveedor'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='codigo_barra',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='created',
            field=models.DateTimeField(null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repuesto',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='marca',
            field=models.CharField(blank=True, default='general', max_length=120),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='marca_veh',
            field=models.CharField(blank=True, default='xxx', max_length=100, null=True, verbose_name='Marca Vehículo'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='medida',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='oem',
            field=models.CharField(blank=True, default='oem', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='origen_repuesto',
            field=models.CharField(blank=True, default='sin-origen', max_length=100, null=True, verbose_name='Origen del Repuesto'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='posicion',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='precio_costo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='referencia',
            field=models.CharField(blank=True, default='no-tiene', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='tipo_de_motor',
            field=models.TextField(blank=True, default='zzzzzz', null=True, verbose_name='Tipo de Motor'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='unidad',
            field=models.CharField(default='pieza', max_length=20),
        ),
        migrations.AddField(
            model_name='repuestoexterno',
            name='activo',
            field=models.BooleanField(default=True, help_text='Desactivar si ya no está disponible'),
        ),
        migrations.AddField(
            model_name='repuestoexterno',
            name='codigo_proveedor',
            field=models.CharField(blank=True, help_text='SKU o código del proveedor', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='repuestoexterno',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repuestos_externos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='repuestoexterno',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción o notas adicionales', null=True),
        ),
        migrations.AddField(
            model_name='repuestoexterno',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='repuestoexterno',
            name='fecha_creacion',
            field=models.DateTimeField(null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repuestoexterno',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='repuestoexterno',
            name='proveedor_nombre',
            field=models.CharField(blank=True, help_text="Si es 'otro', especificar nombre", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='repuestoexterno',
            name='url_producto',
            field=models.URLField(blank=True, help_text='Link directo al producto', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='repuestoexterno',
            name='veces_usado',
            field=models.IntegerField(default=0, help_text='Contador de veces que se ha referenciado'),
        ),
        migrations.AddField(
            model_name='repuestoexterno',
            name='vehiculos_compatibles',
            field=models.ManyToManyField(blank=True, related_name='repuestos_externos_compatibles', to='core.vehiculo'),
        ),
        migrations.AlterField(
            model_name='repuestoexterno',
            name='nombre',
            field=models.CharField(help_text='Nombre del repuesto', max_length=255),
        ),
        migrations.AlterField(
            model_name='repuestoexterno',
            name='precio_referencial',
            field=models.DecimalField(decimal_places=0, help_text='Precio de referencia en pesos', max_digits=10),
        ),
        migrations.AlterField(
            model_name='repuestoexterno',
            name='proveedor',
            field=models.CharField(choices=[('mundo_repuestos', '🛒 Mundo Repuestos'), ('autoplanet', '🚗 AutoPlanet'), ('otro', '📦 Otro Proveedor')], default='otro', max_length=50),
        ),
        migrations.CreateModel(
            name='RepuestoEnStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposito', models.CharField(default='bodega-principal', max_length=80)),
                ('proveedor', models.CharField(blank=True, max_length=120)),
                ('stock', models.IntegerField(default=0)),
                ('reservado', models.IntegerField(default=0)),
                ('precio_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventario.repuesto')),
            ],
            options={
                'unique_together': {('repuesto', 'deposito', 'proveedor')},
            },
        ),
        migrations.CreateModel(
            name='StockMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso', 'ingreso'), ('salida', 'salida'), ('reserva', 'reserva'), ('liberacion', 'liberacion')], max_length=20)),
                ('cantidad', models.IntegerField()),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('referencia', models.CharField(blank=True, max_length=120)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('repuesto_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.repuestoenstock')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComponenteRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.CharField(blank=True, max_length=200)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.componente')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.repuesto')),
            ],
            options={
                'unique_together': {('componente', 'repuesto')},
            },
        ),
        migrations.CreateModel(
            name='RepuestoAplicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.CharField(blank=True, max_length=80)),
                ('motor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Motor')),
                ('carroceria', models.CharField(blank=True, max_length=100, null=True, verbose_name='Carrocería')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='inventario.repuesto')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehiculoversion')),
            ],
            options={
                'unique_together': {('repuesto', 'version')},
            },
        ),
    ]
