# Generated by Django 5.2.5 on 2025-11-21 15:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
from datetime import datetime


def get_default_datetime():
    return datetime.now()


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administraciontaller',
            options={'ordering': ['-fecha_actualizacion'], 'verbose_name': 'Administración del Taller', 'verbose_name_plural': 'Administraciones de Taller'},
        ),
        migrations.AddField(
            model_name='administraciontaller',
            name='bloqueo_temporal_horas',
            field=models.PositiveIntegerField(default=1, help_text='Horas de bloqueo después de exceder intentos máximos'),
        ),
        migrations.AddField(
            model_name='administraciontaller',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='administraciontaller',
            name='dias_validez_password',
            field=models.PositiveIntegerField(default=90, help_text='Días de validez de la contraseña (0 = sin expiración)'),
        ),
        migrations.AddField(
            model_name='administraciontaller',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='administraciontaller',
            name='fecha_creacion',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='administraciontaller',
            name='imagen_fondo',
            field=models.ImageField(blank=True, help_text='Imagen de fondo para el panel principal (recomendado: 1920x1080px)', null=True, upload_to='fondos/'),
        ),
        migrations.AddField(
            model_name='administraciontaller',
            name='intentos_login_maximos',
            field=models.PositiveIntegerField(default=5, help_text='Máximo número de intentos de login fallidos'),
        ),
        migrations.AddField(
            model_name='administraciontaller',
            name='logo_principal_png',
            field=models.ImageField(blank=True, help_text='Logo principal en formato PNG (recomendado: 200x80px)', null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='administraciontaller',
            name='logo_principal_svg',
            field=models.FileField(blank=True, help_text='Logo principal en formato SVG (vectorial, mejor calidad)', null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='administraciontaller',
            name='logo_secundario_png',
            field=models.ImageField(blank=True, help_text='Logo secundario en formato PNG (recomendado: 150x60px)', null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='administraciontaller',
            name='mostrar_estadisticas_publicas',
            field=models.BooleanField(default=True, help_text='Mostrar estadísticas en el panel principal'),
        ),
        migrations.AddField(
            model_name='administraciontaller',
            name='notificaciones_email',
            field=models.BooleanField(default=True, help_text='Enviar notificaciones por email'),
        ),
        migrations.AddField(
            model_name='administraciontaller',
            name='permitir_registro_usuarios',
            field=models.BooleanField(default=False, help_text='Permitir que nuevos usuarios se registren automáticamente'),
        ),
        migrations.AddField(
            model_name='administraciontaller',
            name='requiere_cambio_password',
            field=models.BooleanField(default=False, help_text='Forzar cambio de contraseña en próximo login'),
        ),
        migrations.AddField(
            model_name='administraciontaller',
            name='rut',
            field=models.CharField(blank=True, help_text='RUT del taller', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='administraciontaller',
            name='sesion_timeout_minutos',
            field=models.PositiveIntegerField(default=30, help_text='Tiempo de inactividad antes de cerrar sesión (minutos)'),
        ),
        migrations.AddField(
            model_name='administraciontaller',
            name='tema_por_defecto',
            field=models.CharField(choices=[('piedra', 'Piedra (Oscuro)'), ('plum', 'Plum (Oscuro)'), ('cyan', 'Cyan (Claro)'), ('sand', 'Sand (Claro)'), ('sage', 'Sage (Claro)'), ('sky', 'Sky (Claro)')], default='piedra', help_text='Tema de color por defecto para nuevos usuarios', max_length=20),
        ),
    ]
