# Generated by Django 5.2.5 on 2025-01-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_alter_administraciontaller_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administraciontaller',
            name='ver_mensajes',
            field=models.BooleanField(default=True, help_text='Permitir visualización de mensajes'),
        ),
        migrations.AddField(
            model_name='administraciontaller',
            name='ver_avisos',
            field=models.BooleanField(default=True, help_text='Permitir visualización de avisos'),
        ),
    ]








