# Generated by Django 5.2.5 on 2025-11-21 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_problema', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('subcomponentes_sugeridos', models.JSONField(blank=True, null=True)),
                ('aceptado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_aceptacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('componentes', models.ManyToManyField(related_name='diagnosticos', to='core.componente')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticoComponenteAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_mano_obra', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Unitario')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.accion')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.componente')),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones_componentes', to='diagnosticos.diagnostico')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticoRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('reservado', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('componente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.componente')),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos', to='diagnosticos.diagnostico')),
                ('repuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.repuesto')),
                ('repuesto_externo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosticos', to='inventario.repuestoexterno')),
            ],
        ),
    ]
