# Generated by Django 5.2.5 on 2025-11-21 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosticos', '0001_initial'),
        ('inventario', '0002_alter_repuestoexterno_options_repuesto_carroceria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosticorepuesto',
            name='componente',
        ),
        migrations.AddField(
            model_name='diagnosticorepuesto',
            name='repuesto_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.repuestoenstock'),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='visible',
            field=models.BooleanField(default=True, help_text='Indica si el diagnóstico debe mostrarse en las listas', verbose_name='Visible'),
        ),
        migrations.AlterField(
            model_name='diagnosticocomponenteaccion',
            name='cantidad',
            field=models.IntegerField(default=1, help_text='Número de veces que se realizará esta acción (ej: cambiar 4 bujías)', verbose_name='Cantidad'),
        ),
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcomponente', models.CharField(max_length=100)),
                ('accion', models.CharField(max_length=200)),
                ('tiempo_estimado_minutos', models.PositiveIntegerField()),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnosticos.diagnostico')),
            ],
        ),
    ]
