#!/bin/bash
# ayuda_motos.sh - Ayuda para gestión de talleres de motos

echo "🏍️ ==============================================="
echo "   GESTIÓN DE TALLERES DE MOTOS"
echo "🏍️ ==============================================="
echo ""
echo "📋 Scripts disponibles:"
echo ""
echo "   🏍️ ./convertir_a_motos.sh <contenedor>"
echo "      Convierte un taller de autos a motos"
echo "      Ejemplo: ./convertir_a_motos.sh cliente_solutioncar"
echo ""
echo "   🚗 ./revertir_a_autos.sh <contenedor>"
echo "      Revierte un taller de motos a autos"
echo "      Ejemplo: ./revertir_a_autos.sh cliente_solutioncar"
echo ""
echo "   🔧 ./inject_motos.sh <contenedor>"
echo "      Inyección directa de archivos de motos"
echo "      Ejemplo: ./inject_motos.sh cliente_solutioncar"
echo ""
echo "📋 Contenedores disponibles:"
docker ps -a --format "table {{.Names}}\t{{.Status}}\t{{.Image}}" | grep -E "(cliente_|taller_)"
echo ""
echo "📁 Archivos de motos:"
echo "   - otros/archivos_motos/panel_principal.html"
echo "   - otros/archivos_motos/vehiculo-desde-abajo.svg"
echo "   - otros/archivos_motos/motor.svg"
echo ""
echo "💡 Ejemplos de uso:"
echo "   # Convertir solutioncar a motos"
echo "   ./convertir_a_motos.sh cliente_solutioncar"
echo ""
echo "   # Ver todos los contenedores"
echo "   docker ps -a"
echo ""
echo "   # Ver logs de un contenedor"
echo "   docker logs -f cliente_solutioncar"
echo ""
echo "🔍 Verificar conversión:"
echo "   1. Accede a tu aplicación web"
echo "   2. Verifica que aparecen iconos de motos 🏍️"
echo "   3. Revisa el plano interactivo (debe mostrar moto)"
echo "   4. Confirma que el panel dice 'Pizarra de Trabajos - Motos'"
