# Generated by Django 5.2.5 on 2025-11-21 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trabajos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonoGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('mecanico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.mecanico')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajos.trabajo')),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionBonoMecanico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('mecanico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_bono', to='usuarios.mecanico')),
            ],
        ),
        migrations.CreateModel(
            name='PagoMecanico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('mecanico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.mecanico')),
            ],
        ),
    ]
