# Generated by Django 5.2.5 on 2025-11-21 15:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonos', '0001_initial'),
        ('trabajos', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcepcionBonoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(help_text='Razón por la cual este trabajo no genera bonos', verbose_name='Motivo de la Excepción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Excepción de Bono por Trabajo',
                'verbose_name_plural': 'Excepciones de Bonos por Trabajo',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AlterModelOptions(
            name='bonogenerado',
            options={'ordering': ['-fecha_generacion'], 'verbose_name': 'Bono Generado', 'verbose_name_plural': 'Bonos Generados'},
        ),
        migrations.AlterModelOptions(
            name='configuracionbonomecanico',
            options={'ordering': ['mecanico__user__first_name', 'mecanico__user__last_name'], 'verbose_name': 'Configuración de Bono por Mecánico', 'verbose_name_plural': 'Configuraciones de Bonos por Mecánico'},
        ),
        migrations.AlterModelOptions(
            name='pagomecanico',
            options={'ordering': ['-fecha_pago'], 'verbose_name': 'Pago a Mecánico', 'verbose_name_plural': 'Pagos a Mecánicos'},
        ),
        migrations.AddField(
            model_name='bonogenerado',
            name='fecha_generacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bonogenerado',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bonogenerado',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='bonogenerado',
            name='porcentaje_aplicado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Porcentaje Aplicado (%)'),
        ),
        migrations.AddField(
            model_name='bonogenerado',
            name='tipo_bono',
            field=models.CharField(choices=[('porcentaje', 'Porcentaje de Mano de Obra'), ('fijo', 'Cantidad Fija')], default='porcentaje', max_length=20, verbose_name='Tipo de Bono'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bonogenerado',
            name='total_mano_obra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Mano de Obra del Trabajo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuracionbonomecanico',
            name='cantidad_fija',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Cantidad fija a pagar por cada trabajo entregado', max_digits=10, null=True, verbose_name='Cantidad Fija'),
        ),
        migrations.AddField(
            model_name='configuracionbonomecanico',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='configuracionbonomecanico',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='configuracionbonomecanico',
            name='notas',
            field=models.TextField(blank=True, help_text='Notas adicionales sobre esta configuración', null=True, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='configuracionbonomecanico',
            name='porcentaje_mano_obra',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Porcentaje de la mano de obra del trabajo (ej: 10.00 = 10%)', max_digits=5, null=True, verbose_name='Porcentaje (%)'),
        ),
        migrations.AddField(
            model_name='configuracionbonomecanico',
            name='tipo_bono',
            field=models.CharField(choices=[('porcentaje', 'Porcentaje de Mano de Obra'), ('fijo', 'Cantidad Fija')], default='porcentaje', max_length=20, verbose_name='Tipo de Bono'),
        ),
        migrations.AddField(
            model_name='pagomecanico',
            name='bonos_aplicados',
            field=models.ManyToManyField(help_text='Bonos que se están pagando con este pago', related_name='pagos', to='bonos.bonogenerado', verbose_name='Bonos Aplicados'),
        ),
        migrations.AddField(
            model_name='pagomecanico',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('otro', 'Otro')], default='efectivo', max_length=20, verbose_name='Método de Pago'),
        ),
        migrations.AddField(
            model_name='pagomecanico',
            name='notas',
            field=models.TextField(blank=True, help_text='Notas adicionales sobre este pago', null=True, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='pagomecanico',
            name='registrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AlterField(
            model_name='bonogenerado',
            name='mecanico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonos_generados', to='usuarios.mecanico', verbose_name='Mecánico'),
        ),
        migrations.AlterField(
            model_name='bonogenerado',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto del Bono'),
        ),
        migrations.AlterField(
            model_name='bonogenerado',
            name='pagado',
            field=models.BooleanField(default=False, help_text='Indica si este bono ya fue pagado', verbose_name='Pagado'),
        ),
        migrations.AlterField(
            model_name='bonogenerado',
            name='trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonos_generados', to='trabajos.trabajo', verbose_name='Trabajo'),
        ),
        migrations.AlterField(
            model_name='configuracionbonomecanico',
            name='activo',
            field=models.BooleanField(default=True, help_text='Si está desactivado, este mecánico no recibirá bonos automáticos', verbose_name='Bonos Activos'),
        ),
        migrations.AlterField(
            model_name='configuracionbonomecanico',
            name='mecanico',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_bono', to='usuarios.mecanico', verbose_name='Mecánico'),
        ),
        migrations.AlterField(
            model_name='pagomecanico',
            name='fecha_pago',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Pago'),
        ),
        migrations.AlterField(
            model_name='pagomecanico',
            name='mecanico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='usuarios.mecanico', verbose_name='Mecánico'),
        ),
        migrations.AlterField(
            model_name='pagomecanico',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Pagado'),
        ),
        migrations.AddIndex(
            model_name='bonogenerado',
            index=models.Index(fields=['mecanico', 'pagado'], name='bonos_bonog_mecanic_9c8016_idx'),
        ),
        migrations.AddIndex(
            model_name='bonogenerado',
            index=models.Index(fields=['fecha_generacion'], name='bonos_bonog_fecha_g_2e1952_idx'),
        ),
        migrations.AddIndex(
            model_name='pagomecanico',
            index=models.Index(fields=['mecanico', 'fecha_pago'], name='bonos_pagom_mecanic_19bf2a_idx'),
        ),
        migrations.AddField(
            model_name='excepcionbonotrabajo',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='excepcionbonotrabajo',
            name='trabajo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='excepcion_bono', to='trabajos.trabajo', verbose_name='Trabajo'),
        ),
    ]
