# Generated by Django 5.2.5 on 2025-11-21 15:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
        ('inventario', '0002_alter_repuestoexterno_options_repuesto_carroceria_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'ordering': ['-fecha_compra', '-creado_en'], 'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.AlterModelOptions(
            name='compraitem',
            options={'verbose_name': 'Item de Compra', 'verbose_name_plural': 'Items de Compra'},
        ),
        migrations.AddField(
            model_name='compra',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='fecha_compra',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='compra',
            name='fecha_recibida',
            field=models.DateField(blank=True, help_text='Fecha cuando se recibió la mercancía', null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Observaciones sobre la compra'),
        ),
        migrations.AddField(
            model_name='compraitem',
            name='fecha_recibido',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compraitem',
            name='recibido',
            field=models.BooleanField(default=False, help_text='¿Ya se recibió este item?'),
        ),
        migrations.AddField(
            model_name='compraitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Cantidad × Precio unitario', max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compra',
            name='proveedor',
            field=models.CharField(help_text='Nombre del proveedor', max_length=200),
        ),
        migrations.AlterField(
            model_name='compraitem',
            name='cantidad',
            field=models.PositiveIntegerField(help_text='Cantidad comprada'),
        ),
        migrations.AlterField(
            model_name='compraitem',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, help_text='Precio por unidad', max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='compraitem',
            unique_together={('compra', 'repuesto')},
        ),
    ]
