# Generated by Django 5.2.5 on 2025-11-21 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('diagnosticos', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('iniciado', 'Iniciado'), ('trabajando', 'Trabajando'), ('completado', 'Completado'), ('entregado', 'Entregado')], default='iniciado', max_length=20)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('diagnostico', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trabajo', to='diagnosticos.diagnostico')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='TrabajoAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.BooleanField(default=False)),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.accion')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.componente')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones', to='trabajos.trabajo')),
            ],
        ),
        migrations.CreateModel(
            name='TrabajoRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('repuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.repuesto')),
                ('repuesto_externo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.repuestoexterno')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos', to='trabajos.trabajo')),
            ],
        ),
    ]
