# Generated by Django 5.2.5 on 2025-11-21 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_prefijorepuesto'),
        ('diagnosticos', '0002_remove_diagnosticorepuesto_componente_and_more'),
        ('inventario', '0002_alter_repuestoexterno_options_repuesto_carroceria_and_more'),
        ('trabajos', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='componentes',
            field=models.ManyToManyField(blank=True, related_name='trabajos', to='core.componente'),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='lectura_kilometraje_actual',
            field=models.IntegerField(blank=True, help_text='Lectura del kilometraje al ingresar el vehículo', null=True, verbose_name='Kilometraje Actual'),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='mecanicos',
            field=models.ManyToManyField(blank=True, related_name='trabajos', to='usuarios.mecanico'),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='visible',
            field=models.BooleanField(default=True, help_text='Indica si el trabajo debe mostrarse en las listas', verbose_name='Visible'),
        ),
        migrations.AddField(
            model_name='trabajoaccion',
            name='cantidad',
            field=models.IntegerField(default=1, help_text='Número de veces que se realizará esta acción (ej: cambiar 4 bujías)', verbose_name='Cantidad'),
        ),
        migrations.AddField(
            model_name='trabajoaccion',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trabajoaccion',
            name='precio_mano_obra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Unitario'),
        ),
        migrations.AddField(
            model_name='trabajorepuesto',
            name='completado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trabajorepuesto',
            name='componente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.componente'),
        ),
        migrations.AddField(
            model_name='trabajorepuesto',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trabajorepuesto',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabajorepuesto',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='diagnostico',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trabajo', to='diagnosticos.diagnostico'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trabajorepuesto',
            name='repuesto_externo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajos', to='inventario.repuestoexterno'),
        ),
        migrations.CreateModel(
            name='TrabajoAbono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('otro', 'Otro')], default='efectivo', max_length=20)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción o nota del abono', null=True)),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='trabajos.trabajo')),
                ('usuario', models.ForeignKey(help_text='Usuario que registró el abono', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abono de Trabajo',
                'verbose_name_plural': 'Abonos de Trabajos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='TrabajoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.TextField(help_text='Descripción del concepto adicional', verbose_name='Concepto')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('descuento', models.BooleanField(default=False, help_text='Si está marcado, este monto se restará del total en lugar de sumarlo', verbose_name='Es Descuento')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adicionales', to='trabajos.trabajo')),
                ('usuario', models.ForeignKey(help_text='Usuario que registró el concepto adicional', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Concepto Adicional',
                'verbose_name_plural': 'Conceptos Adicionales',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='TrabajoFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='trabajos/fotos/%Y/%m/%d')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='trabajos.trabajo')),
            ],
        ),
    ]
