# Generated by Django 5.2.5 on 2025-11-21 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente_Taller',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cliente del Taller',
                'verbose_name_plural': 'Clientes del Taller',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(editable=False, max_length=255, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hijos', to='core.componente')),
            ],
        ),
        migrations.CreateModel(
            name='ComponenteAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_mano_obra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.accion')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.componente')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.PositiveIntegerField()),
                ('vin', models.CharField(blank=True, max_length=50, null=True)),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('descripcion_motor', models.CharField(blank=True, max_length=100, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente_taller')),
            ],
        ),
        migrations.CreateModel(
            name='VehiculoVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=80)),
                ('modelo', models.CharField(max_length=120)),
                ('anio_desde', models.IntegerField()),
                ('anio_hasta', models.IntegerField()),
                ('motor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Motor')),
                ('carroceria', models.CharField(blank=True, max_length=100, null=True, verbose_name='Carrocería')),
            ],
            options={
                'unique_together': {('marca', 'modelo', 'anio_desde', 'anio_hasta')},
            },
        ),
        migrations.AddIndex(
            model_name='componente',
            index=models.Index(fields=['codigo'], name='core_compon_codigo_3b48c2_idx'),
        ),
        migrations.AddConstraint(
            model_name='componente',
            constraint=models.UniqueConstraint(fields=('padre', 'nombre'), name='unique_nombre_por_padre'),
        ),
        migrations.AlterUniqueTogether(
            name='componenteaccion',
            unique_together={('componente', 'accion')},
        ),
        migrations.AddConstraint(
            model_name='vehiculo',
            constraint=models.UniqueConstraint(fields=('cliente', 'placa'), name='unique_vehiculo_cliente_placa'),
        ),
    ]
