# Generated by Django 5.2.5 on 2025-11-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrefijoRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra', models.CharField(help_text="Palabra clave a buscar en el nombre o posición (ej. 'freno')", max_length=100, unique=True)),
                ('abreviatura', models.CharField(help_text="Abreviatura para el SKU (ej. 'FRE')", max_length=10)),
            ],
        ),
    ]
