# Generated by Django 5.2.5 on 2025-11-21 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('rol', models.CharField(choices=[('mecanico', 'Mecánico'), ('vendedor', 'Vendedor'), ('admin', 'Administrador')], default='mecanico', max_length=20)),
                ('puede_ver_diagnosticos', models.BooleanField(default=True)),
                ('puede_ver_trabajos', models.BooleanField(default=True)),
                ('puede_ver_pos', models.BooleanField(default=True)),
                ('puede_ver_compras', models.BooleanField(default=True)),
                ('puede_ver_inventario', models.BooleanField(default=True)),
                ('puede_ver_administracion', models.BooleanField(default=True)),
                ('crear_clientes', models.BooleanField(default=True)),
                ('crear_vehiculos', models.BooleanField(default=True)),
                ('aprobar_diagnosticos', models.BooleanField(default=False)),
                ('gestionar_usuarios', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mecanico', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
